project_id = "abepwxatllszoapfmccl"

[functions.edit-photo]
verify_jwt = true

[functions.blocket-sync]
verify_jwt = true

[functions.generate-car-description]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.create-stripe-customer]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-billing-info]
verify_jwt = true

[functions.report-usage-to-stripe]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.init-templates]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
