project_id = "abepwxatllszoapfmccl"

[functions.edit-photo]
verify_jwt = true

[functions.segment-car]
verify_jwt = true

[functions.add-reflection]
verify_jwt = true

[functions.blocket-sync]
verify_jwt = true

[functions.generate-car-description]
verify_jwt = true

[functions.translate-text]
verify_jwt = true

[functions.create-stripe-customer]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-billing-info]
verify_jwt = true

[functions.report-usage-to-stripe]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.init-templates]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.check-admin-ip]
verify_jwt = false

[functions.send-email-verification]
verify_jwt = false

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.save-admin-ip]
verify_jwt = false

[functions.get-verification-status]
verify_jwt = false

[functions.remove-logo-background]
verify_jwt = true

[functions.create-customer-checkout]
verify_jwt = true

[functions.manage-leads]
verify_jwt = true

[functions.create-background-template]
verify_jwt = true

[functions.track-trial-usage]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.get-admin-customers]
verify_jwt = true

[functions.create-initial-stripe-customer]
verify_jwt = false

[functions.reconcile-usage]
verify_jwt = false
